Compiler = g++-7
Flags = -std=c++17 -Wall
OutputName = MatrixTest

Matrix: MatrixClass.cpp
	$(Compiler) MatrixClass.cpp $(Flags) -o $(OutputName)
	clear
	sleep 3
	./$(OutputName)


Compile:
	$(Compiler) MatrixClass.cpp $(Flags) -o $(OutputName)
